### ISSUE TITLE
some minor bugs after first look at the website 

### ISSUE THREAD

**Issue by him1411** [crux-bphc/fest-manager#231]
1) cursor lagging when going through animations of different heads 
2) circle and click icons both are visible when going to click button 
3) competitions tab opening contacts page ( not on the sidebar but the main page itself ) 

@rogeredthat @aero31aero

**Comment by rogeredthat** [comment]
@aero31aero here. Removed custom cursor reslving 1 and 2.

If 3 was on phone, then its resolved now. We disabled the buildings on phone because of lack of certain APIs.

**Comment by him1411** [comment]
all the issues are of desktop website. I've cleared the cache and open the website again. 3) is not solved 
![](https://i.imgur.com/W5HDCVi.png)

after clicking the link 

![](https://i.imgur.com/XvdD4Iz.png)

**Comment by him1411** [comment]
these issues resolved @rogeredthat  @aero31aero  . Website is smoother than ever. No lag whatsoever. No animation delay. All the pages opening properly. Great Work
